import ExitDraftModeLink from "@/components/exit-draftmode";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { draftMode } from "next/headers";
import { SessionProvider } from "@/lib/contentful/session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider
          locale="en-US"
          enableLiveUpdates={draftMode().isEnabled}
        >
          {draftMode().isEnabled ? (
            <p className="bg-orange-200 py-4 px-[6vw]">
              Draft mode is on! <ExitDraftModeLink className="underline" />
            </p>
          ) : null}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
